name: Node CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test PR
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: yarn install, build, and test
        run: |
          yarn install
          yarn run build --if-present
          yarn test
        env:
          CI: true
